# dowload linux.zip
# https://github.com/godotengine/godot-builds/releases/download/4.2-beta4/Godot_v4.2-beta4_linux.x86_64.zip

name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  # build_game_linux_and_windows:
  #   name: Build for Linux & Windows
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       platform: [ windows, linux ]
  #   steps:
  #   - name: Download, unzip, and add Godot to path
  #     run: |
  #       # prepare godot version and platform
  #       GODOT_VERSION="4.2-stable"
  #       GODOT_EXPORT_TEMPLATES_VERSION="4.2.stable"
  #       BUILD_PLATFORM="linux.x86_64"
  #       FILENAME="Godot_v${GODOT_VERSION}_${BUILD_PLATFORM}"
  #       EXPORT_TEMPLATES_FILENAME="Godot_v${GODOT_VERSION}_export_templates"

  #       # download (later: cache)
  #       # godot
  #       curl -LO https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/${FILENAME}.zip

  #       # export templates
  #       curl -LO https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/${EXPORT_TEMPLATES_FILENAME}.tpz

  #       # decompress
  #       unzip ${FILENAME}.zip
  #       unzip ${EXPORT_TEMPLATES_FILENAME}.tpz
  #       ls -la templates

  #       # add to path
  #       mkdir -p $HOME/.local/bin
  #       mkdir -p $HOME/.local/share/godot/export_templates/${GODOT_EXPORT_TEMPLATES_VERSION}
  #       echo "$HOME/.local/bin" >> $GITHUB_PATH
  #       cp ${FILENAME} $HOME/.local/bin/godot
  #       cp templates/* $HOME/.local/share/godot/export_templates/${GODOT_EXPORT_TEMPLATES_VERSION}

  #       # test it
  #       # godot -h

  #   - uses: actions/checkout@v3

  #   - name: Use Godot from path
  #     run: |
  #       mkdir dist
  #       godot --headless --export-release ${{ matrix.platform }}
  #       ls -la dist

  #   - name: Upload Artifact
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: Client - ${{ matrix.platform }}
  #       path: dist/worlds_collide.*


  build_game_macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:

    - name: Cache Godot & Templates
      id: cache-godot-mac
      uses: actions/cache@v3
      with:
        path: ~/.local/bin/godot
        key: ${{ runner.os }}-godot

    - name: Download, unzip, and add Godot to path
      if: steps.cache-godot-mac.outputs.cache-hit != 'true'
      run: |
        # prepare godot version and platform
        GODOT_VERSION="4.2-stable"
        GODOT_EXPORT_TEMPLATES_VERSION="4.2.stable"
        BUILD_PLATFORM="macos.universal"
        FILENAME="Godot_v${GODOT_VERSION}_${BUILD_PLATFORM}"
        EXPORT_TEMPLATES_FILENAME="Godot_v${GODOT_VERSION}_export_templates"

        # download
        # godot
        curl -LO https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/${FILENAME}.zip

        # export templates
        # curl -LO https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/${EXPORT_TEMPLATES_FILENAME}.tpz

        # decompress
        unzip ${FILENAME}.zip Godot.app/Contents/MacOS/Godot
        # unzip ${EXPORT_TEMPLATES_FILENAME}.tpz templates/macos.zip

        # copy godot executable to a common location
        mkdir -p $HOME/.local/bin
        echo $PATH
        export PATH=$PATH:$HOME/.local/bin
        echo $PATH
        cp ./Godot.app/Contents/MacOS/Godot $HOME/.local/bin/godot

        # make the templates dir and copy the ones we need there
        # mkdir -p "$HOME/Library/Application Support/Godot/export_templates/${GODOT_EXPORT_TEMPLATES_VERSION}"
        # cp templates/macos.zip "$HOME/Library/Application Support/Godot/export_templates/${GODOT_EXPORT_TEMPLATES_VERSION}/macos.zip"

        # test it
        godot -h

    # - uses: actions/checkout@v4

    # - name: Use Godot.app
    #   run: |
    #     mkdir dist
    #     # $HOME/Godot.app/Contents/MacOS/Godot --headless --export-release mac
    #     godot --headless --export-release mac

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Client - macOS
    #     path: dist/worlds_collide.*
