# dowload linux.zip
# https://github.com/godotengine/godot-builds/releases/download/4.2-beta4/Godot_v4.2-beta4_linux.x86_64.zip

name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  install_godot:
    runs-on: ubuntu-latest
    steps:
    - name: Download, unzip, and add Godot to path
      run: |
        # prepare godot version and platform
        GODOT_VERSION="4.2-rc2"
        BUILD_PLATFORM="linux.x86_64"
        FILENAME="Godot_v${GODOT_VERSION}_${BUILD_PLATFORM}"

        # download (later: cache)
        curl -LO https://github.com/godotengine/godot-builds/releases/download/${GODOT_VERSION}/${FILENAME}.zip

        # decompress
        unzip ${FILENAME}.zip

        # add shell helpers
        mkdir -p $HOME/.local/bin
        cp $(FILENAME) $HOME/.local/bin/godot
        echo ::add-path::$HOME/.local/bin

        # test it
        godot -h

    - name: Use Godot from path
      run: godot -h

  # build_from_linux:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       platform: [ windows ]
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         lfs: true
  #     - name: Build
  #       id: build
  #       uses: manleydev/build-godot-action@v1.5.0
  #       with:
  #         name: worlds_collide
  #         preset: ${{ matrix.platform }}
  #         # debugMode: "true"
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: Client - ${{ matrix.platform }}
  #         path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
  ## TODO: build godot without using a container
  # build_from_macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: maxim-lobanov/setup-xcode@v1
  #       with:
  #         xcode-version: latest-stable
  #     - uses: actions/checkout@v2
  #       with:
  #         lfs: true
  #     - name: Build
  #       id: build
  #       uses: manleydev/build-godot-action@v1.5.0
  #       with:
  #         name: worlds_collide
  #         preset: mac
  #         # debugMode: "true"
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: Client - macOS
  #         path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
